version: 2
updates:
  - package-ecosystem: terraform
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    directory: '/tf-infrastructure/'
    open-pull-requests-limit: 3

  - package-ecosystem: 'npm'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    directory: '/'
    open-pull-requests-limit: 3

  - package-ecosystem: 'gomod'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    directory: '/'
    open-pull-requests-limit: 3
