service: bamboo-tracker

plugins:
  - serverless-offline
  - serverless-deployment-bucket

custom:
  timesheetS3Key: timesheet.yml

provider:
  name: aws
  runtime: go1.x
  stackTags:
    ENVIRONMENT: ${self:provider.stage}
    PROJECT: ${self:service}-${self:provider.stage}
  deploymentBucket:
    name: ${self:service}-deployment-bucket-${self:provider.region}-${self:provider.stage}
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  logRetentionInDays: 7
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
      Resource:
        Fn::Join:
          - '/'
          - - !GetAtt ['TimesheetsBucket', Arn]
            - ${self:custom.timesheetS3Key}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  uploadTimesheet:
    handler: bin/timesheetUploader
    events:
      - schedule: cron(0 17 ? * MON-FRI *)
    environment:
      BAMBOO_HOST: https://companyname.bamboohr.com
      BAMBOO_USERNAME: TODO
      BAMBOO_PASSWORD: TODO
      TIMESHEETS: |
        tuesday:
          - start: 9:00
            end: 12:00
          - start: 12:30
            end: 16:35
        wednesday:
          - start: 9:00
            end: 12:00
          - start: 12:30
            end: 16:35
        thursday:
          - start: 9:00
            end: 12:00
          - start: 12:30
            end: 16:35

resources:
  Resources:
    TimesheetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-timesheets-${self:provider.stage}
        AccessControl: Private
