name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 10
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v3
    - name: Set up Go 1.13
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.6
      id: go

    - name: Build
      run: make build
    
    - name: Unit tests
      run: make test

    - name: Prepare offline env vars
      run: make prepare-offline-env

    - name: Prepare offline CF template
      run: AWS_ACCESS_KEY=mock AWS_SECRET_ACCESS_KEY=mock make package STAGE=offline

    - name: Setup Cloud Formation Linter with Latest Version
      uses: scottbrenner/cfn-lint-action@v2

    - name: Print the Cloud Formation Linter Version & run Linter.
      run: |
        cfn-lint --version
        cfn-lint -t ./serverless/cloudformation-template-update-stack.json
